- name: Import geerlingguy.security role.
  ansible.builtin.import_role:
    name: geerlingguy.security
  vars:
    # For https://github.com/geerlingguy/ansible-role-security
    security_autoupdate_mail_to: public@demid.dev
    security_sudoers_passworded:
      - "{{ username }}"
    security_ssh_port: "{{ ssh_port }}"
    security_ssh_allowed_users:
      - "{{ username }}"

- name: Install security packages.
  ansible.builtin.apt:
    name:
      - libpam-tmpdir
      - apt-listchanges
      - debian-goodies
      - debsecan
      - debsums
      - chkrootkit
    update_cache: true
    state: present

- name: By default allow only ssh for the primary IP.
  community.general.ufw:
    rule: allow
    port: "{{ ssh_port }}"
    proto: tcp
    dest: "{{ primary_ip_address }}"
  tags: ufw

- name: By default allow only http/https for the secondary IP.
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
    dest: "{{ secondary_ip_address }}"
  loop:
    - 80
    - 443
  tags: ufw

- name: Set default firewall policy.
  community.general.ufw:
    state: enabled
    policy: reject
    dest: "{{ item }}"
  loop:
    - "{{ primary_ip_address }}"
    - "{{ secondary_ip_address }}"
  tags: ufw
