- name: Import devsec.hardening.os_hardening role.
  import_role:
    name: devsec.hardening.os_hardening
  vars:
    # For https://github.com/dev-sec/ansible-collection-hardening/tree/master/roles/os_hardening
    sysctl_overwrite:
      # Enable IPv4 traffic forwarding for Docker and Kubernetes.
      net.ipv4.ip_forward: 1
    os_auth_pw_max_age: 99999

- name: Import devsec.hardening.ssh_hardening role.
  import_role:
    name: devsec.hardening.ssh_hardening
  vars:
    # For https://github.com/dev-sec/ansible-collection-hardening/tree/master/roles/ssh_hardening
    ssh_server_ports:
      - '{{ ssh_port }}'
    ssh_permit_tunnel: true
    ssh_allow_tcp_forwarding: 'yes'
    ssh_allow_agent_forwarding: true
    ssh_allow_users: '{{ username }}'

- name: Import ansible-role-security role.
  import_role:
    name: ansible-role-security
  vars:
    # For https://github.com/geerlingguy/ansible-role-security
    security_autoupdate_mail_to: "public@demid.dev"
    security_sudoers_passworded:
      - "{{ username }}"
    security_ssh_port: "{{ ssh_port }}"
    security_ssh_allowed_users:
      - "{{ username }}"

- name: Install security packages.
  apt:
    name:
      - libpam-tmpdir
      - apt-listchanges
      - debian-goodies
      - debsecan
      - debsums
      - chkrootkit
    update_cache: yes
    state: present

- name: By default allow only ssh.
  ufw:
    rule: allow
    port: "{{ ssh_port }}"
    proto: tcp

- name: Set default firewall policy.
  ufw:
    state: enabled
    policy: reject

- name: Clone Lynis.
  git:
    repo: https://github.com/CISOfy/Lynis
    dest: "{{ home_directory }}/lynis"
