- name: Import ansible-role-security role.
  import_role:
    name: ansible-role-security

- name: Clone Lynis.
  git:
    repo: https://github.com/CISOfy/Lynis
    dest: "{{ home_directory }}/Soft/lynis"

- name: Install security packages.
  apt:
    name:
      - libpam-tmpdir
      - apt-listchanges
      - debian-goodies
      - debsecan
      - debsums
      - chkrootkit
    update_cache: yes
    state: present

- name: By default allow only ssh.
  ufw:
    rule: allow
    port: "{{ security_ssh_port }}"
    proto: tcp

- name: Set firewall default policy.
  ufw:
    state: enabled
    policy: reject
