- name: Install packages necessary for Jekyll.
  become: true
  ansible.builtin.apt:
    name:
      - ruby-full
      - build-essential
      - zlib1g-dev
    state: present

# See https://rvm.io/ ##########################################################

- name: Install rvm GPG keys
  ansible.builtin.shell:
    cmd: gpg --keyserver keyserver.ubuntu.com --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
    executable: /bin/bash
  tags: rvm

- name: Install curl -sSL https://get.rvm.io | bash -s stable
  ansible.builtin.shell: curl -sSL https://get.rvm.io | bash -s stable
  tags: rvm

- name: Install ruby 3.0.0 with rvm
  ansible.builtin.shell: /home/{{ username }}/.rvm/bin/rvm install 3.0.0
  tags: rvm

- name: Set ruby 3.0.0 as default
  ansible.builtin.shell: /home/{{ username }}/.rvm/bin/rvm alias create default 3.0.0
  tags: rvm

################################################################################

- name: Install bundler.
  become: true
  become_user: "{{ username }}"
  community.general.gem:
    name: bundler
    install_dir: "{{ home_directory }}/gems"
    user_install: false

- name: Install jekyll.
  become: true
  become_user: "{{ username }}"
  community.general.gem:
    name: jekyll
    install_dir: "{{ home_directory }}/gems"
    user_install: false
