---
- name: Install go-jira.
  shell: GO111MODULE=on /usr/local/go/bin/go install github.com/go-jira/jira/cmd/jira@latest

- name: Copy "jira" executable.
  copy:
    src: "{{ home_directory }}/go/bin/jira"
    dest: "{{ home_directory }}/.local/bin/jira"
    remote_src: true
    mode: a+x

- name: Remove go build directory.
  become: true
  file:
    path: "{{ home_directory }}/go"
    state: absent

- name: Create go-jira config directory.
  file:
    path: "{{ home_directory }}/.jira.d"
    state: directory

- name: Copy go-jira config.
  template:
    src: go_jira_config.yml.j2
    dest: "{{ home_directory }}/.jira.d/config.yml"
  tags: go_jira_config
