---
- name: Install go-jira.
  ansible.builtin.shell: GO111MODULE=on /usr/local/go/bin/go install github.com/go-jira/jira/cmd/jira@latest

- name: Copy "jira" executable.
  ansible.builtin.copy:
    src: "{{ home_directory }}/go/bin/jira"
    dest: "{{ home_directory }}/.local/bin/jira"
    remote_src: true
    mode: a+x

- name: Remove go build directory.
  become: true
  ansible.builtin.file:
    path: "{{ home_directory }}/go"
    state: absent

- name: Create go-jira config directory.
  ansible.builtin.file:
    path: "{{ home_directory }}/.jira.d"
    state: directory

- name: Copy go-jira config.
  ansible.builtin.template:
    src: go_jira_config.yml.j2
    dest: "{{ home_directory }}/.jira.d/config.yml"
  tags: go_jira_config

- name: Create "Quickopen" directory.
  ansible.builtin.file:
    path: "{{ home_directory }}/Soft/Quickopen"
    state: directory

- name: Copy "jiraopen" script.
  ansible.builtin.copy:
    src: jiraopen.py
    dest: "{{ home_directory }}/Soft/Quickopen/jiraopen.py"
