---

- name: Set the hostname.
  hostname:
    name: "{{ server_hostname }}"

- name: Run "apt-get update, dist-upgrade and autoremove".
  apt:
    update_cache: yes
    upgrade: dist
    autoremove: yes

- name: Install server packages.
  apt:
    name: "{{ server_packages }}"
    state: present

- name: Increase inotify user limit.
  sysctl: name=fs.inotify.max_user_watches value=524288 sysctl_set=yes
