- name: Set the hostname.
  ansible.builtin.hostname:
    name: "{{ server_hostname }}"

- name: Run "apt-get update, dist-upgrade and autoremove".
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
    autoremove: true

- name: Install server packages.
  ansible.builtin.apt:
    name: "{{ server_packages }}"
    state: present

- name: Increase inotify user limit.
  ansible.posix.sysctl: name=fs.inotify.max_user_watches value=524288 sysctl_set=yes
