- name: Import rootless_docker role.
  ansible.builtin.import_role:
    name: rootless_docker
  vars:
    docker_user: searx

- name: Clone my searx fork.
  become: true
  become_user: searx
  ansible.builtin.git:
    repo: https://github.com/{{ github_username }}/searxng-docker
    dest: "{{ docker_user_info.home }}/searxng-docker"
  ignore_errors: true

- name: Set a secret key.
  become: true
  ansible.builtin.shell: sed -i "s|ultrasecretkey|$(openssl rand -hex 32)|g" searxng/settings.yml
  args:
    chdir: "{{ docker_user_info.home }}/searxng-docker"

- name: Add necessary entries to the .env file.
  become: true
  ansible.builtin.lineinfile:
    path: "{{ docker_user_info.home }}/searxng-docker/.env"
    line: "{{ item }}"
  loop:
    - "SEARXNG_HOSTNAME={{ searx_domain }}"

- name: Create and start searx services.
  become: true
  become_user: searx
  community.general.docker_compose:
    project_src: "{{ docker_user_info.home }}/searxng-docker"
    docker_host: "unix://run/user/{{ docker_user_info.uid }}/docker.sock"
  vars:
    ansible_python_interpreter: "{{ docker_user_info.home }}/venv/bin/python"
