---
# Playbook for setting up everything.

- name: Set up CIDE.
  hosts: cide
  vars_files:
    - .vars.private.yml
  roles:
    - role: common
      become: yes
      tags: common
    - role: security
      become: yes
      tags: security
    - role: development
      tags: development
    - role: code-server
      tags: code-server
    - role: garden
      tags: garden
    - role: nextcloud
      tags: nextcloud
    - role: syncthing
      become: yes
      tags: syncthing
    - role: opencraft
      tags: opencraft
