roles:
  - name: geerlingguy.nodejs
    version: 6.0.0
  - name: geerlingguy.security
    version: 2.1.0
  - name: mrlesmithjr.netplan
    version: v0.3.0
  - name: geerlingguy.docker
    version: 6.1.0
