---
- name: Install Syncthing public signing key.
  apt_key:
    url: https://syncthing.net/release-key.gpg
    state: present

- name: Add Syncthing repo.
  apt_repository:
    repo: deb https://apt.syncthing.net/ syncthing stable
    state: present

- name: Install Syncthing.
  apt:
    name: syncthing
    update_cache: true
    state: present

- name: Add syncthing.conf supervisor service config.
  template:
    src: syncthing.conf.j2
    dest: /etc/supervisor/conf.d/syncthing.conf

- name: Reload supervisor.
  service: name=supervisor state=reloaded

- name: Start syncthing process.
  supervisorctl:
    name: syncthing
    state: started
