- name: Install Syncthing public signing key.
  ansible.builtin.apt_key:
    url: https://syncthing.net/release-key.gpg
    state: present

- name: Add Syncthing repo.
  ansible.builtin.apt_repository:
    repo: deb https://apt.syncthing.net/ syncthing stable
    state: present

- name: Install Syncthing.
  ansible.builtin.apt:
    name: syncthing
    update_cache: true
    state: present

- name: Add syncthing.conf supervisor service config.
  ansible.builtin.template:
    src: syncthing.conf.j2
    dest: /etc/supervisor/conf.d/syncthing.conf

- name: Reload supervisor.
  ansible.builtin.service: name=supervisor state=reloaded

- name: Start syncthing process.
  community.general.supervisorctl:
    name: syncthing
    state: started
