- name: Import mrlesmithjr.netplan role.
  become: true
  ansible.builtin.import_role:
    name: mrlesmithjr.netplan
  vars:
    netplan_enabled: true
    netplan_config_file: /etc/netplan/01-netcfg.yaml
    netplan_renderer: networkd
    netplan_configuration:
      network:
        version: 2
        renderer: networkd
        ethernets:
          enp5s0:
            addresses: "{{ netplan_addresses }}"
            routes:
              - on-link: true
                to: 0.0.0.0/0
                via: 213.133.101.97
            gateway6: fe80::1
            nameservers:
              addresses:
                - 213.133.100.100
                - 213.133.98.98
                - 213.133.99.99
                - 2a01:4f8:0:1::add:9999
                - 2a01:4f8:0:1::add:1010
                - 2a01:4f8:0:1::add:9898
