server_hostname: cide
server_dependencies: 
  - htop
  - sudo
  - git
  - ufw
  - neofetch
  - python3-dev
  - python3-pip
  - python3-virtualenv
  - build-essential
  - python3-venv
  - screen
  - ripgrep
