- name: Download nvim and put it to /usr/bin
  become: true
  get_url:
    url: https://github.com/neovim/neovim/releases/download/v0.9.4/nvim.appimage
    dest: /usr/bin/nvim
    mode: 0755

- name: Create "nvim" directory.
  ansible.builtin.file:
    path: "{{ home_directory }}/.config/nvim"
    state: directory

- name: Copy "init.lua".
  ansible.builtin.copy:
    src: init.lua
    dest: "{{ home_directory }}/.config/nvim/init.lua"
  tags: vimrc

- name: Copy Lua modules.
  copy:
    src: lua/user
    dest: "{{ home_directory }}/.config/nvim/lua"
  tags: vimrc
