- name: Import rootless_docker role.
  ansible.builtin.import_role:
    name: rootless_docker
  vars:
    docker_user: "{{ firefly_username }}"

- name: Clone my firefly fork.
  become: true
  become_user: "{{ firefly_username }}"
  ansible.builtin.git:
    repo: https://github.com/{{ github_username }}/firefly-docker
    dest: "{{ docker_user_info.home }}/firefly"
  ignore_errors: true

- name: Generate .env.
  become: true
  become_user: "{{ firefly_username }}"
  ansible.builtin.template:
    src: .env.j2
    dest: "{{ docker_user_info.home }}/firefly/.env"

- name: Generate .db.env.
  become: true
  become_user: "{{ firefly_username }}"
  ansible.builtin.template:
    src: .db.env.j2
    dest: "{{ docker_user_info.home }}/firefly/.db.env"

- name: Create and start firefly services.
  become: true
  become_user: "{{ firefly_username }}"
  community.general.docker_compose:
    project_src: "{{ docker_user_info.home }}/firefly"
    docker_host: "unix://run/user/{{ docker_user_info.uid }}/docker.sock"
  vars:
    ansible_python_interpreter: "{{ docker_user_info.home }}/venv/bin/python"
