- name: Clone private documentation.
  git:
    repo: "git@gitlab.com:opencraft/documentation/private.git"
    dest: "{{ home_directory }}/Projects/opencraft_private_documentation"
    accept_hostkey: yes
  ignore_errors: yes

- name: Install a symlink.
  shell: make ssh
  args:
    chdir: "{{ home_directory }}/Projects/opencraft_private_documentation/ssh_config"

- name: Install HashiCorp public signing key.
  become: yes
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Add HashiCorp repo.
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com focal main"
    state: present

- name: Install Vault.
  become: yes
  apt:
    name: vault
    update_cache: yes
    state: present

# TODO: Rework. This actually won't fetch keys because of prompt, so has to be runned manually.
- name: Fetch keys.
  shell: make keys
  args:
    chdir: "{{ home_directory }}/Projects/opencraft_private_documentation/ssh_config"

- name: Install oc_log_helper.
  shell: "{{ pipx }} install oc_log_helper --system-site-packages"
  ignore_errors: yes
  tags: yay

- name: Create "add_shortcut" directory.
  file:
    path: "{{ home_directory }}/Soft/add_shortcut"
    state: directory
  tags: yay

- name: Copy "add_shortcut.py".
  copy:
    src: add_shortcut.py
    dest: "{{ home_directory }}/Soft/add_shortcut/add_shortcut.py"
  tags: yay

- name: Run "add_shortcut.py".
  shell: python3 add_shortcut.py 'Add log record' 'oc_log_helper log-work' '<Super>T'
  args:
    chdir: "{{ home_directory }}/Soft/add_shortcut/"
  ignore_errors: yes
