---
- name: Clone private documentation.
  ansible.builtin.git:
    repo: git@gitlab.com:opencraft/documentation/private.git
    dest: "{{ home_directory }}/Projects/opencraft_private_documentation"
    accept_hostkey: true
  ignore_errors: true

- name: Install a symlink.
  ansible.builtin.shell: make ssh
  args:
    chdir: "{{ home_directory }}/Projects/opencraft_private_documentation/ssh_config"
  ignore_errors: true

- name: Add OBS project repository.
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:obsproject/obs-studio

- name: Install OBS Studio.
  become: true
  ansible.builtin.apt:
    name: obs-studio
    update_cache: true
    state: present

- name: Create "Sprint Updates" directory.
  ansible.builtin.file:
    path: "{{ home_directory }}/Videos/Sprint Updates"
    state: directory

- name: Create "Other recordings" directory.
  ansible.builtin.file:
    path: "{{ home_directory }}/Documents/Other recordings"
    state: directory

- name: Install HashiCorp public signing key.
  become: true
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Add HashiCorp repo.
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com focal main
    state: present

- name: Install Vault.
  become: true
  ansible.builtin.apt:
    name: vault
    update_cache: true
    state: present

# TODO: Rework. This actually won't fetch keys because of prompt, so has to be runned manually.
- name: Fetch keys.
  ansible.builtin.shell: make keys
  args:
    chdir: "{{ home_directory }}/Projects/opencraft_private_documentation/ssh_config"

- name: Install oc_log_helper.
  ansible.builtin.shell: "{{ pipx }} install oc_log_helper --system-site-packages"
  ignore_errors: true

# TODO: convert shortcut installer into a separate role and move this to the localhost role.
- name: Install todoist_helper.
  ansible.builtin.shell: "{{ pipx }} install todoist_helper --system-site-packages"
  ignore_errors: true

- name: Create "add_shortcut" directory.
  ansible.builtin.file:
    path: "{{ home_directory }}/Soft/add_shortcut"
    state: directory
  tags: shortcuts

- name: Copy "add_shortcut.py".
  ansible.builtin.copy:
    src: add_shortcut.py
    dest: "{{ home_directory }}/Soft/add_shortcut/add_shortcut.py"
  tags: shortcuts

# https://ubuntuforums.org/showthread.php?t=2106567
# https://gitlab.com/rubdos/gsettings-desktop-schemas/-/blob/5ea3e6a64cffdc634a5eff55d0ae3a384b937eeb/schemas/org.gnome.desktop.wm.keybindings.gschema.xml.in
- name: Unset some default keybindings.
  ansible.builtin.shell: "gsettings set org.gnome.desktop.wm.keybindings {{ item }} []"
  loop:
    - switch-input-source
  tags: shortcuts

- name: Disable <Super>s keybinding.
  ansible.builtin.shell: gsettings set org.gnome.shell.keybindings toggle-overview []
  tags: shortcuts

- name: Reset all shortcuts.
  ansible.builtin.shell: gsettings reset org.gnome.settings-daemon.plugins.media-keys custom-keybindings
  tags: shortcuts

- name: Add log work shortcut.
  ansible.builtin.shell: python3 add_shortcut.py 'Add log record' 'oc_log_helper log-work' '<Super>T'
  args:
    chdir: "{{ home_directory }}/Soft/add_shortcut/"
  tags: shortcuts

# TODO: convert shortcut installer into a separate role and move this to the localhost role.
- name: Add start tracking shortcut.
  ansible.builtin.shell: python3 add_shortcut.py 'Start tracking' 'oc_log_helper start-tracking' '<Super>S'
  args:
    chdir: "{{ home_directory }}/Soft/add_shortcut/"
  tags: shortcuts

# TODO: convert shortcut installer into a separate role and move this to the localhost role.
- name: Add shared todoist helper shortcut.
  ansible.builtin.shell: "python3 add_shortcut.py 'Add obsidian task' 'todoist_helper add-obsidian -i {{ home_directory }}/Cloud/0x29a/_todo/Inbox.md' '<Super>Space'"
  args:
    chdir: "{{ home_directory }}/Soft/add_shortcut/"
  tags: shortcuts

# TODO: convert shortcut installer into a separate role and move this to the localhost role.
- name: Add personal todoist helper shortcut.
  ansible.builtin.shell: python3 add_shortcut.py 'Add personal todoist task' 'todoist_helper add' '<Super>Y'
  args:
    chdir: "{{ home_directory }}/Soft/add_shortcut/"
  tags: shortcuts
