---
- name: Install packages necessary for Jekyll.
  become: true
  apt:
    name:
      - ruby
      - ruby-full
      - ruby-dev
      - rubygems
    state: present

- name: Install bundler.
  become: true
  gem:
    name: bundler

- name: Install jekyll.
  become: true
  gem:
    name: jekyll

- name: Clone garden repo.
  git:
    repo: git@github.com:{{ github_username }}/garden.git
    dest: "{{ home_directory }}/Projects/garden"

- name: Install garden gems.
  bundler:
    deployment_mode: true
    state: present
    chdir: "{{ home_directory }}/Projects/garden"
    executable: /bin/bundle2.7
