---
- name: Install packages necessary for Jekyll.
  become: true
  ansible.builtin.apt:
    name:
      - ruby
      - ruby-full
      - ruby-dev
      - rubygems
    state: present

- name: Install bundler.
  become: true
  community.general.gem:
    name: bundler

- name: Install jekyll.
  become: true
  community.general.gem:
    name: jekyll

- name: Clone garden repo.
  ansible.builtin.git:
    repo: git@github.com:{{ github_username }}/garden.git
    dest: "{{ projects_directory }}/garden"

- name: Install garden gems.
  community.general.bundler:
    deployment_mode: true
    state: present
    chdir: "{{ projects_directory }}/garden"
    executable: /bin/bundle2.7
