- name: Install neovim.
  become: true
  ansible.builtin.apt:
    name: neovim
    state: present

- name: Create "autoload" directory.
  ansible.builtin.file:
    path: "{{ home_directory }}/.local/share/nvim/site/autoload"
    state: directory

- name: Create "nvim" directory.
  ansible.builtin.file:
    path: "{{ home_directory }}/.config/nvim"
    state: directory

- name: Download vim-plug.
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ home_directory }}/.local/share/nvim/site/autoload/plug.vim"

- name: Copy "init.vim".
  ansible.builtin.copy:
    src: init.vim
    dest: "{{ home_directory }}/.config/nvim/init.vim"
