---
- name: Create soft directory
  file:
    path: "{{ home_directory }}/Soft"
    state: directory

- name: Create projects directory
  file:
    path: "{{ home_directory }}/Projects"
    state: directory

- name: Install zsh.
  become: yes
  apt:
    name: zsh
    state: present

- name: Check if .oh-my-zsh exists.
  stat:
    path: "{{ home_directory }}/.oh-my-zsh"
  register: stat_oh_my_zsh_result

- name: Install Oh My Zsh.
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  become_user: "{{ username }}"
  when: not stat_oh_my_zsh_result.stat.exists

- name: Copy zshrc.
  template:
    src: .zshrc.j2
    dest: "{{ home_directory }}/.zshrc"

- name: Change shell to zsh.
  become: yes
  user:
    name: "{{ username }}"
    shell: /bin/zsh

- name: Check if zsh history exist.
  stat:
    path: "{{ home_directory }}/.zsh_history"
  register: stat_zsh_history_result

- name: Copy zsh history.
  copy:
    src: .zsh_history
    dest: "{{ home_directory }}/.zsh_history"
  when: not stat_zsh_history_result.stat.exists

- name: Check if pyenv exists.
  stat:
    path: "{{ home_directory }}/.pyenv"
  register: stat_pyenv_result

- name: Install pyenv.
  shell: git clone https://github.com/pyenv/pyenv.git ~/.pyenv
  when: not stat_pyenv_result.stat.exists

- name: Check if pyenv-virtualenv exists.
  stat:
    path: "{{ home_directory }}/.pyenv/plugins/pyenv-virtualenv"
  register: stat_pyenv_virtualenv_result

- name: Install pyenv-virtualenv.
  shell: "git clone https://github.com/pyenv/pyenv-virtualenv.git {{ home_directory }}/.pyenv/plugins/pyenv-virtualenv"
  when: not stat_pyenv_virtualenv_result.stat.exists

- name: Add HashiCorp key.
  become: yes
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Add HashiCorp repo.
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release | lower }} main"
    state: present

- name: Install HashiCorp tools.
  become: yes
  apt:
    name:
      - vagrant
      - terraform
      - vault
    update_cache: yes
    state: present

- name: Add Docker key.
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repo.
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable"
    state: present

- name: Install Docker.
  become: yes
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: yes
    state: present

- name: Ensure user is added to the docker group.
  become: yes
  user:
    name: "{{ username }}"
    groups: docker
    append: true

- name: Add VirtualBox key.
  become: yes
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present

- name: Add VirtualBox repo.
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release | lower }} contrib"
    state: present

- name: Install VirtualBox.
  become: yes
  apt:
    name:
      - linux-headers-generic
      - linux-headers-5.4.0-77-generic
      - virtualbox-6.1
      - virtualbox-dkms
    update_cache: yes
    state: present

- name: Install pipx.
  shell: python3 -m pip install --user pipx

- name: Install ipython.
  shell: "{{ pipx }} install ipython"
  ignore_errors: yes

- name: Install docker-compose.
  shell: "{{ pipx }} install docker-compose"
  ignore_errors: yes

- name: Download and install ufw-docker.
  become: yes
  get_url:
    url: https://github.com/chaifeng/ufw-docker/raw/master/ufw-docker
    dest: /usr/local/bin/ufw-docker
    mode: a+x

- name: Install ufw-docker rules
  become: yes
  shell: ufw-docker install

- name: Restart ufw
  become: yes
  service:
    name: ufw
    state: restarted

- name: Import the nodejs role
  import_role:
    name: ansible-role-nodejs
  tags: nodejs
  become: yes

- name: nvm
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
  tags: nodejs

- name: Install some js dependencies.
  become: yes
  apt:
    name:
      - libxrender1:i386
      - libxtst6:i386
      - libxi6:i386
    update_cache: yes
    state: present
  tags: nodejs
