---
- name: Create "Soft" directory.
  ansible.builtin.file:
    path: "{{ home_directory }}/Soft"
    state: directory

- name: Set default firewall policy.
  become: true
  community.general.ufw:
    state: enabled
    policy: reject

- name: Restart ufw.
  become: true
  ansible.builtin.service:
    name: ufw
    state: restarted

- name: Run "apt-get update, dist-upgrade and autoremove".
  become: true
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
    autoremove: true

- name: Install local packages.
  become: true
  ansible.builtin.apt:
    name: "{{ local_packages }}"
    state: present
  tags: local_packages

- name: Remove local packages.
  become: true
  ansible.builtin.apt:
    name: "{{ local_packages_to_remove }}"
    state: absent
  tags: local_packages_remove

- name: Install local snap packages.
  become: true
  community.general.snap:
    name: "{{ local_snap_packages }}"
    classic: true

- name: Set git username for the local CIDE repo.
  community.general.git_config:
    name: user.name
    repo: .
    scope: local
    value: "{{ github_username }}"

- name: Set git email for the local CIDE repo.
  community.general.git_config:
    name: user.email
    repo: .
    scope: local
    value: "{{ github_email }}"

- name: Change remote URL to SSH.
  community.general.git_config:
    name: remote.origin.url
    repo: .
    scope: local
    value: git@github.com:{{ github_username }}/cide.git

- name: Copy SSH config.
  ansible.builtin.copy:
    src: ssh_config
    dest: "{{ home_directory }}/.ssh/config"
  tags: ssh_config

- name: Set up hosts file.
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    line: "{{ item }}"
  with_items: "{{ hosts_entries }}"
  tags: hosts_file

- name: Configure byobu as available shell.
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/shells
    line: /usr/bin/byobu
  tags: terminal

- name: Copy Guake autostart file.
  ansible.builtin.copy:
    src: guake.desktop
    dest: "{{ home_directory }}/.config/autostart/guake.desktop"
  tags: terminal

- name: Import guake preferences.
  ansible.builtin.shell: guake --restore-preferences roles/localhost/files/guake_preferences
  tags: terminal

- name: Copy tmux config.
  ansible.builtin.copy:
    src: .tmux.conf
    dest: "{{ home_directory }}/.byobu/.tmux.conf"
  tags: terminal

- name: Clone tmux-jump.
  ansible.builtin.git:
    repo: https://github.com/schasse/tmux-jump
    dest: "{{ home_directory }}/.tmux-jump"
  tags: terminal

- name: Copy byobu keybindings config.
  ansible.builtin.copy:
    src: keybindings.tmux
    dest: "{{ home_directory }}/.byobu/keybindings.tmux"
  tags: terminal

- name: Disable Gnome animations.
  ansible.builtin.shell: gsettings set org.gnome.desktop.interface enable-animations false

- name: Disable the Dock.
  ansible.builtin.shell: gnome-extensions disable ubuntu-dock@ubuntu.com

- name: Disable desktop icons.
  ansible.builtin.shell: gnome-extensions disable desktop-icons@csoriano

- name: Disable background.
  ansible.builtin.shell: gsettings set org.gnome.desktop.background picture-options 'none'

- name: Set primary background color to black.
  ansible.builtin.shell: gsettings set org.gnome.desktop.background primary-color '#000000'

- name: Set secondary background color to black.
  ansible.builtin.shell: gsettings set org.gnome.desktop.background secondary-color '#000000'

- name: Remove favourites.
  ansible.builtin.shell: gsettings set org.gnome.shell favorite-apps "['firefox.desktop']"

- name: Disable natural scroll.
  ansible.builtin.shell: gsettings set org.gnome.desktop.peripherals.touchpad natural-scroll false

- name: Create "cide" directory.
  ansible.builtin.file:
    path: "{{ home_directory }}/Soft/cide"
    state: directory

# TODO: replace with https://docs.ansible.com/ansible/latest/collections/ansible/builtin/fetch_module.html
# once recursive option implemented.
- name: Download CIDE electron app build.
  ansible.builtin.shell: scp -r {{ username }}@cloud:{{ home_directory }}/Soft/cide/CIDE-linux-x64 {{ home_directory }}/Soft/cide/CIDE-linux-x64

- name: Copy CIDE icon.
  ansible.builtin.copy:
    src: cide.png
    dest: "{{ home_directory }}/Soft/cide/CIDE-linux-x64/cide.png"

- name: Copy cide.desktop.
  become: true
  ansible.builtin.template:
    src: cide.desktop
    dest: /usr/share/applications/cide.desktop

- name: Install Signal public signing key.
  become: true
  ansible.builtin.apt_key:
    url: https://updates.signal.org/desktop/apt/keys.asc
    state: present

- name: Add Signal repo.
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main
    state: present

- name: Install Signal.
  become: true
  ansible.builtin.apt:
    name: signal-desktop
    update_cache: true
    state: present

- name: Install pipx.
  ansible.builtin.shell: python3 -m pip install --user pipx

- name: Install python packages.
  community.general.pipx:
    name: "{{ item }}"
  loop:
    - ipython
    - lolcat
    - black

- name: Inject requests to ipython virtualenv.
  community.general.pipx:
    name: ipython
    state: inject
    inject_packages:
      - requests

- name: Install freetube.
  become: true
  ansible.builtin.apt:
    deb: "{{ freetube_deb_url }}"

- name: Create "obsidian" directory.
  ansible.builtin.file:
    path: "{{ home_directory }}/Soft/obsidian"
    state: directory
  tags: obsidian

- name: Download Obsidian appimage.
  ansible.builtin.get_url:
    url: "{{ obsidian_appimage_url }}"
    dest: "{{ home_directory }}/Soft/obsidian/obsidian"
    mode: a+x
  tags: obsidian

- name: Copy obsidian.desktop.
  become: true
  ansible.builtin.template:
    src: obsidian.desktop
    dest: /usr/share/applications/obsidian.desktop

- name: Install ProtonVPN repo.
  become: true
  ansible.builtin.apt:
    deb: "{{ protonvpn_deb_url }}"
  tags: proton

- name: Install ProtonVPN.
  become: true
  ansible.builtin.apt:
    name: protonvpn
    update_cache: true
    state: present
  tags: proton

- name: Add firejail repository.
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:deki/firejail
  tags: firejail

- name: Install firejail.
  become: true
  ansible.builtin.apt:
    name:
      - firejail
      - firejail-profiles
    update_cache: true
    state: present
  tags: firejail

- name: Create "firefox_jail" directory.
  ansible.builtin.file:
    path: "{{ home_directory }}/firefox_jail"
    state: directory
  tags: firejail

- name: Create firefox launcher.
  become: true
  ansible.builtin.copy:
    src: jailed_firefox
    dest: /usr/local/bin/firefox
    mode: a+x
  tags: firejail
