- name: Create "Soft" directory.
  file:
    path: "{{ home_directory }}/Soft"
    state: directory

- name: Set default firewall policy.
  become: yes
  ufw:
    state: enabled
    policy: reject

- name: Restart ufw.
  become: yes
  service:
    name: ufw
    state: restarted

- name: Run "apt-get update, dist-upgrade and autoremove".
  become: yes
  apt:
    update_cache: yes
    upgrade: dist
    autoremove: yes

- name: Install local packages.
  become: yes
  apt:
    name: "{{ local_packages }}"
    state: present
  tags: local_packages

- name: Remove local packages.
  become: yes
  apt:
    name: "{{ local_packages_to_remove }}"
    state: absent
  tags: local_packages_remove

- name: Install local snap packages.
  become: yes
  snap:
    name: "{{ local_snap_packages }}"
    classic: yes

- name: Set git username for the local CIDE repo.
  git_config:
    name: user.name
    repo: .
    scope: local
    value: "{{ github_username }}"

- name: Set git email for the local CIDE repo.
  git_config:
    name: user.email
    repo: .
    scope: local
    value: "{{ github_email }}"

- name: Change remote URL to SSH.
  git_config:
    name: remote.origin.url
    repo: .
    scope: local
    value: "git@github.com:{{ github_username }}/cide.git"

- name: Copy SSH config.
  copy:
    src: ssh_config
    dest: "{{ home_directory }}/.ssh/config"
  tags: ssh_config

- name: Set up hosts file.
  become: yes
  lineinfile:
    dest: /etc/hosts
    line: '{{ item }}'
  with_items: "{{ hosts_entries }}"
  tags: hosts_file

- name: Configure byobu as available shell.
  become: yes
  lineinfile:
    dest: /etc/shells
    line: /usr/bin/byobu
  tags: terminal

- name: Copy Guake autostart file.
  copy:
    src: guake.desktop
    dest: "{{ home_directory }}/.config/autostart/guake.desktop"
  tags: terminal

- name: Import guake preferences.
  shell: guake --restore-preferences roles/localhost/files/guake_preferences
  tags: terminal

- name: Copy tmux config.
  copy:
    src: .tmux.conf
    dest: "{{ home_directory }}/.byobu/.tmux.conf"
  tags: terminal

- name: Clone tmux-jump.
  git:
    repo: https://github.com/schasse/tmux-jump
    dest: "{{ home_directory }}/.tmux-jump"
  tags: terminal

- name: Copy byobu keybindings config.
  copy:
    src: keybindings.tmux
    dest: "{{ home_directory }}/.byobu/keybindings.tmux"
  tags: terminal

- name: Disable Gnome animations.
  shell: gsettings set org.gnome.desktop.interface enable-animations false

- name: Disable the Dock.
  shell: gnome-extensions disable ubuntu-dock@ubuntu.com

- name: Disable desktop icons.
  shell: gnome-extensions disable desktop-icons@csoriano

- name: Disable background.
  shell: gsettings set org.gnome.desktop.background picture-options 'none'

- name: Set primary background color to black.
  shell: gsettings set org.gnome.desktop.background primary-color '#000000'

- name: Set secondary background color to black.
  shell: gsettings set org.gnome.desktop.background secondary-color '#000000'

- name: Remove favourites.
  shell: gsettings set org.gnome.shell favorite-apps "['firefox.desktop']"

- name: Create "cide" directory.
  file:
    path: "{{ home_directory }}/Soft/cide"
    state: directory

# TODO: replace with https://docs.ansible.com/ansible/latest/collections/ansible/builtin/fetch_module.html
# once recursive option implemented.
- name: Download CIDE electron app build.
  shell: "scp -r {{ username }}@cloud:{{ home_directory }}/Soft/cide/CIDE-linux-x64 {{ home_directory }}/Soft/cide/CIDE-linux-x64"

- name: Copy CIDE icon.
  copy:
    src: cide.png
    dest: "{{ home_directory }}/Soft/cide/CIDE-linux-x64/cide.png"

- name: Copy cide.desktop.
  become: yes
  template:
    src: cide.desktop
    dest: /usr/share/applications/cide.desktop

- name: Install Signal public signing key.
  become: yes
  apt_key:
    url: https://updates.signal.org/desktop/apt/keys.asc
    state: present

- name: Add Signal repo.
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main"
    state: present

- name: Install Signal.
  become: yes
  apt:
    name: signal-desktop
    update_cache: yes
    state: present

- name: Install pipx.
  shell: python3 -m pip install --user pipx

- name: Install ipython.
  shell: "{{ pipx }} install ipython"
  ignore_errors: yes

- name: Install lolcat.
  shell: "{{ pipx }} install lolcat"
  ignore_errors: yes

- name: Install black.
  shell: "{{ pipx }} install black"
  ignore_errors: yes

- name: Install freetube.
  become: yes
  apt:
    deb: "{{ freetube_deb_url }}"

- name: Create "obsidian" directory.
  file:
    path: "{{ home_directory }}/Soft/obsidian"
    state: directory
  tags: obsidian

- name: Download Obsidian appimage.
  get_url:
    url: "{{ obsidian_appimage_url }}"
    dest: "{{ home_directory }}/Soft/obsidian/obsidian"
    mode: a+x
  tags: obsidian

- name: Copy obsidian.desktop.
  become: yes
  template:
    src: obsidian.desktop
    dest: /usr/share/applications/obsidian.desktop

- name: Download tridactyl native messenger installation shell script.
  get_url:
    url: "{{ tridactyl_native_messenger_url }}"
    dest: /tmp/trinativeinstall.sh
  tags: tridactyl

- name: Run tridactyl native messenger installation shell script.
  shell: "sh /tmp/trinativeinstall.sh {{ tridactyl_version }}"
  tags: tridactyl

- name: Copy tridactyl config.
  copy:
    src: .tridactylrc
    dest: "{{ home_directory }}/.tridactylrc"
  tags:
    - tridactyl
    - tridactylrc
