- name: Create "Soft" directory.
  file:
    path: "{{ home_directory }}/Soft"
    state: directory

- name: Run "apt-get update, dist-upgrade and autoremove".
  become: yes
  apt:
    update_cache: yes
    upgrade: dist
    autoremove: yes

- name: Install local packages.
  become: yes
  apt:
    name: "{{ local_packages }}"
    state: present
  tags: local_packages

- name: Install local snap packages.
  become: yes
  snap:
    name: "{{ local_snap_packages }}"
    classic: yes

- name: Set git username for the local CIDE repo.
  git_config:
    name: user.name
    repo: .
    scope: local
    value: "{{ github_username }}"

- name: Set git email for the local CIDE repo.
  git_config:
    name: user.email
    repo: .
    scope: local
    value: "{{ github_email }}"

- name: Change remote URL to SSH.
  git_config:
    name: remote.origin.url
    repo: .
    scope: local
    value: "git@github.com:{{ github_username }}/cide.git"

- name: Copy Guake autostart file.
  copy:
    src: guake.desktop
    dest: "{{ home_directory }}/.config/autostart/guake.desktop"

- name: Import guake preferences.
  shell: guake --restore-preferences roles/localhost/files/guake_preferences

- name: Disable Gnome animations.
  shell: gsettings set org.gnome.desktop.interface enable-animations false

- name: Disable background.
  shell: gsettings set org.gnome.desktop.background picture-options 'none'
