- name: Add VSCodium key.
  become: true
  ansible.builtin.apt_key:
    url: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
    state: present

- name: Add VSCodium repo.
  become: true
  ansible.builtin.apt_repository:
    repo: deb https://download.vscodium.com/debs vscodium main
    state: present

- name: Install VSCodium.
  become: true
  ansible.builtin.apt:
    name: codium
    update_cache: true
    state: present

- name: Copy settings.
  ansible.builtin.copy:
    src: codium_settings.json
    dest: "{{ home_directory }}/.config/VSCodium/User/settings.json"
