---
# Based on https://go.dev/doc/install

- name: Remove local go directory.
  become: true
  ansible.builtin.file:
    path: /usr/local/go
    state: absent

- name: Download and extract go.
  become: true
  ansible.builtin.unarchive:
    src: "{{ go_tar_download_url }}"
    dest: /usr/local
    remote_src: true
