# Based on: https://github.com/nezhar/wordpress-docker-compose/blob/master/docker-compose.yml
services:
  wp:
    image: wordpress:6.7
    ports:
      - ${IP}:${PORT}:80
    volumes:
      - ./wp_php.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql:9.1
    command: [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"

  pma:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      UPLOAD_LIMIT: 50M
    ports:
      - ${IP}:8781:80
    links:
      - db:db
    volumes:
      - ./pma_php.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./pma_config.php:/etc/phpmyadmin/config.user.inc.php

volumes:
  db_data:
