local_packages:
  - python3-venv
  - ruby-full
  - htop
  - curl
  - xclip
  - tmux
  - byobu
  - autossh
  - supervisor
  - guake
  - gnome-tweaks
  - flameshot

local_packages_to_remove:
  - thunderbird
  - rhythmbox

local_snap_packages: []

obsidian_appimage_url: https://github.com/obsidianmd/obsidian-releases/releases/download/v0.13.23/Obsidian-0.13.23.AppImage
freetube_deb_url: https://github.com/FreeTubeApp/FreeTube/releases/download/v0.16.0-beta/freetube_0.16.0_amd64.deb
