# Playbook for setting up everything.
- name: Set up CIDE.
  hosts: cide
  user: demid
  vars_files:
    - ../.vars.private.yml
  roles:
    - role: common
      become: true
      tags: common
    - role: security
      become: true
      tags: security
    - role: additional-ip
      tags: additional-ip
    - role: golang
      tags: golang
    - role: zsh
      vars:
        cide_environment: cloud
      tags: zsh
    - role: neovim
      tags: neovim
    - role: development
      tags: development
    - role: k3s
      tags: k3s
    - role: searx
      tags: searx
    - role: bookwyrm
      tags: bookwyrm
    - role: isso
      tags: isso
    - role: genesis
      tags: genesis
    - role: plausible
      tags: plausible
    - role: caddy
      tags: caddy
    - role: syncthing
      tags: syncthing
    - role: restic
      tags: restic
    - role: opencraft
      tags: opencraft
    - role: monitoring
      tags: monitoring
