# Playbook for setting up everything.
- name: Set up CIDE.
  hosts: cide
  user: demid
  vars_files:
    - ../.vars.private.yml
  roles:
    - role: common
      become: true
      tags: common
    - role: security
      become: true
      tags: security
    - role: golang
      tags: golang
    - role: zsh
      vars:
        cide_environment: cloud
      tags: zsh
    - role: neovim
      tags: neovim
    - role: development
      tags: development
    - role: code-server
      tags: code-server
    - role: garden
      tags: garden
    - role: syncthing
      become: true
      tags: syncthing
    - role: opencraft
      tags: opencraft
    - role: web_template
      tags: web_template
