---

- name: Set up local machine.
  hosts: localhost
  connection: local
  vars_files:
    - ../.vars.private.yml
  roles:
    - role: localhost
      tags: localhost
    - role: vscodium
      become: yes
      tags: vscodium
