---

- name: Set up local machine.
  hosts: localhost
  connection: local
  vars_files:
    - ../.vars.private.yml
  roles:
    - role: localhost
      tags: localhost
    - role: vscodium
      tags: vscodium
    - role: zsh
      tags: zsh
    - role: syncthing
      become: yes
      tags: syncthing
    - role: opencraft_local
      tags: opencraft
