---
- name: Set up local machine.
  hosts: localhost
  connection: local
  vars_files:
    - ../.vars.private.yml
  roles:
    - role: localhost
      tags: localhost
    - role: vscodium
      tags: vscodium
    - role: zsh
      tags: zsh
    - role: vim
      tags: vim
    - role: syncthing
      become: true
      tags: syncthing
    - role: opencraft_local
      tags: opencraft
    - role: golang
      tags: golang
    - role: go-jira
      tags: go-jira
    - role: taskwarrior
      tags: taskwarrior
    - role: firejail
      tags: firejail
