- name: Download Syncthing public signing key.
  get_url:
    url: https://syncthing.net/release-key.gpg
    dest: /usr/share/keyrings/syncthing-archive-keyring.gpg

- name: Add Syncthing repo.
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/syncthing-archive-keyring.gpg] https://apt.syncthing.net/ syncthing candidate"
    state: present

- name: Install Syncthing.
  apt:
    name: syncthing
    update_cache: yes
    state: present

- name: Add syncthing.conf supervisor service config.
  template:
    src: syncthing.conf.j2
    dest: /etc/supervisor/conf.d/syncthing.conf

- name: Reload supervisor.
  service: name=supervisor state=reloaded

- name: Start syncthing process.
  supervisorctl:
    name: syncthing
    state: started
